import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/game/sim.ts';import {expeditionAI,routineRest} from '../src/game/journeys.ts';
import {decodeGame,encodeGame} from '../src/game/persistence.ts';
function fixture(){const g=new Game();g.reset(123456);g.enterIsland();g.world.heights.fill(4);g.state.buildings=[g.makeBld('townhall',0,38,0)];g.state.units=g.state.units.filter(u=>u.team===0).slice(0,1);g.state.weather='clear';g.rebuildWalk();return g;}
function drive(g,u,seconds=90){for(let i=0;i<seconds*30;i++){g.state.time+=1/30;g.navBudget=10;g.workerAI(u,1/30);if(u.carry===0)return;} }
test('log carriers unload from all sides of a solid town hall without walking inside it',()=>{for(const [dx,dz] of [[30,30],[-30,-30],[30,-30],[-30,30],[0,30]]){const g=fixture(),u=g.state.units[0];Object.assign(u,{x:dx,z:38+dz,y:4,order:'return',node:null,carry:8,carryType:'wood'});const stock=g.tribe(0).wood;drive(g,u);assert.equal(u.carry,0,`carrier from ${dx}/${dz}`);assert.equal(g.tribe(0).wood,stock+8);}});
test('crowded halls are reachable and unfinished storage never traps delivery',()=>{const g=fixture(),u=g.state.units[0];const bad=g.makeBld('warehouse',25,50,0);bad.build=.3;g.state.buildings.push(bad,g.makeBld('hut',12,38,0));g.rebuildWalk();Object.assign(u,{x:30,z:60,y:4,order:'return',node:null,carry:8,carryType:'wood'});drive(g,u);assert.equal(u.carry,0);});
test('loaded saved carriers resume the same delivery safely',()=>{let g=fixture(),u=g.state.units[0];Object.assign(u,{x:35,z:73,y:4,order:'return',node:null,carry:8,carryType:'wood'});g=decodeGame(encodeGame(g));g.world.heights.fill(4);g.rebuildWalk();u=g.state.units[0];drive(g,u);assert.equal(u.carry,0);});
test('hungry returning expeditions keep moving at night and preserve cargo',()=>{const g=fixture(),u=g.state.units[0];Object.assign(u,{x:40,z:78,y:4,order:'explore',carry:8,carryType:'wood',expedition:{food:0,returning:false,forage:0}});g.clockState=()=>({period:'Night'});const x=u.x;g.navBudget=10;assert.ok(expeditionAI(g,u,1));assert.equal(u.expedition.returning,true);assert.ok(u.x!==x||u.z!==78);assert.equal(u.carry,8);assert.equal(routineRest(g,u,1),false);});
test('natural rival collapse does not end a continuing world',()=>{const g=fixture();g.state.time=500;g.state.tribes[1].alive=false;g.state.tribes[2].alive=false;g.checkVictory();assert.equal(g.state.ended,null);});
test('children can mature within a session while old saves remain playable',()=>{const g=fixture(),u=g.state.units[0];u.maturesAt=g.state.time+16*1800;g.tickPeople(.1);assert.ok(u.maturesAt<=g.state.time+360);g.state.time+=361;g.tickPeople(.1);assert.equal(u.maturesAt,undefined);});
test('exhausted forage recovers more slowly and overharvesting reduces its next crop',()=>{const g=fixture(),n=g.state.forage[0];Object.assign(n,{amount:0,maxAmt:20,regenT:0,pressure:1});g.state.time=500;g.tickRegen(.1);assert.ok(n.amount<=6);assert.doesNotThrow(()=>decodeGame(encodeGame(g)));});
test('resources have a visible selection report',()=>{const g=fixture();g.clearSelect();g.selectedResource=g.state.trees[0];const h=g.snapshot();assert.equal(h.selection.kind,'resource');assert.equal(h.selection.name,'Tree');});
test('food and hunting assignments search unknown land when no known target exists',()=>{for(const job of ['food','hunt']){const g=fixture(),u=g.state.units[0];g.state.forage=[];g.state.fish=[];g.state.wildlife=[];g.state.buildings=g.state.buildings.filter(b=>b.type==='townhall');g.clearSelect();u.selected=true;g.assignJob(job);assert.equal(u.order,'explore');assert.equal(u.searchJob,job);assert.match(u.workReason,/Searching/);}});
test('winter timber focus outranks routine food when reserves are safe',()=>{const g=fixture(),u=g.state.units[0];g.state.time=1400;g.tribe(0).food=1000;g.tribe(0).wood=10;const source=g.state.trees[0];g.state.trees=[{...source,id:g.id(),x:u.x+12,z:u.z,amount:20}];g.vision.fill(1);g.setLaborPriority('wood');assert.equal(u.order,'gather');assert.equal(u.job,'wood');});
test('new names vary by seed and small-village citizens have given names',async()=>{const {citizenName}=await import('../src/game/people.ts');assert.notEqual(citizenName(123,1,0),citizenName(456,1,0));assert.equal(citizenName(123,1,0).includes(' '),false);});
test('productive farms can be planted on gentle upland slopes',()=>{const g=fixture();g.state.buildings=[];g.state.trees=[];g.state.stones=[];g.state.forage=[];g.height=(x,z)=>10+x*.15;assert.equal(g.placementIssue('farm',0,38),null);g.height=(x,z)=>10+x;assert.match(g.placementIssue('farm',0,38),/slope/);});
test('actual harvesting accumulates pressure rather than only changing a display',()=>{const g=fixture(),u=g.state.units[0],n=g.state.forage[0];Object.assign(n,{x:u.x,z:u.z,amount:10,pressure:0});Object.assign(u,{order:'gather',node:n,job:'food',gatherT:1000,carry:0});g.workerAI(u,.1);assert.ok(n.pressure>0);});
test('unknown tribe identities never leak through the HUD dots',()=>{const g=fixture();g.vision.fill(0);assert.deepEqual(g.snapshot().tribes.map(t=>t.id),[0]);});
test('a line of loaded carriers unloads through a shared crowded frontage',()=>{const g=fixture();g.state.forage=[];g.state.wildlife=[];g.state.trees=[];g.state.stones=[];const first=g.state.units[0];g.state.units=[];for(let i=0;i<10;i++){const u=i?g.spawnUnit('worker',-20+i*1.1,48,0):first;Object.assign(u,{x:-20+i*1.1,z:48,y:4,order:'return',node:null,carry:8,carryType:'wood'});if(!g.state.units.includes(u))g.state.units.push(u);}const stock=g.tribe(0).wood;for(let i=0;i<900;i++){g.state.time+=.1;g.navBudget=10;for(const u of g.state.units)g.workerAI(u,.1);g.separate(.1);}assert.equal(g.state.units.reduce((n,u)=>n+u.carry,0),0);assert.equal(g.tribe(0).wood,stock+80);});
test('hunters take moving prey and bring actual food home',()=>{const g=fixture(),u=g.state.units[0];g.state.forage=[];g.state.fish=[];g.state.trees=[];g.state.stones=[];const prey={...g.state.wildlife.find(c=>c.species==='goat'),id:g.id(),species:'goat',x:12,z:38,y:4,hp:2,maxHp:2,vx:0,vz:0,wanderT:10};g.state.wildlife=[prey];Object.assign(u,{x:0,z:48,y:4});g.vision.fill(2);u.selected=true;g.tribe(0).food=10;const food=g.tribe(0).food;g.assignJob('hunt');for(let i=0;i<1800;i++){g.state.time+=1/30;g.navBudget=10;g.workerAI(u,1/30);g.tickWildlife(1/30);assert.ok(Math.hypot(prey.vx,prey.vz)<=2.51);}assert.equal(prey.hp,0);assert.ok(g.tribe(0).food>food,'the catch must be delivered');});
test('rivals do not arbitrarily kill people or halls when stores dip',()=>{const g=fixture();const hall=g.makeBld('townhall',80,38,1);g.state.buildings.push(hall);g.state.units=[];for(let i=0;i<5;i++)g.spawnUnit('worker',80+i*2,48,1);g.tribe(1).food=0;g.tribe(1).wood=0;const hp=hall.hp;const random=Math.random;try{Math.random=()=>0;for(let i=0;i<10;i++){g.tribe(1).thinkT=0;g.rivalTick(1,.1);}}finally{Math.random=random;}assert.equal(g.popNow(1),5);assert.equal(hall.hp,hp);});
test('delivery frontage never selects a sub-cell point inside a neighboring hut',()=>{const g=fixture(),u=g.state.units[0];g.state.buildings=[];const hall=g.makeBld('townhall',-179.0248,-248.4618,0),store=g.makeBld('warehouse',-186,-248,0);g.state.buildings.push(hall,store,g.makeBld('hut',-174,-244,0),g.makeBld('hut',-178,-242,0),g.makeBld('hut',-187.85,-240.24,0),g.makeBld('hut',-166.90,-250.45,0),g.makeBld('barracks',-169.02,-256.46,0));g.rebuildWalk();Object.assign(u,{x:-172,z:-240,y:4,carry:8,carryType:'wood',order:'return',node:null});const spot=g.interactionSpot(u,hall);if(spot)assert.ok(g.canStep(u,spot.x,spot.z));drive(g,u,180);assert.equal(u.carry,0);});
test('unseen societies cannot place overlapping structures through player fog',()=>{const g=fixture();g.vision.fill(0);const store=g.makeBld('warehouse',80,38,1);g.state.buildings.push(store);assert.match(g.placementIssue('warehouse',80,38,1),/building/);assert.match(g.placementIssue('hut',80,38,2),/building/);});
test('a loaded citizen walks out of a blocked start cell without teleporting cargo',()=>{const g=fixture(),u=g.state.units[0];Object.assign(u,{x:0,z:38,y:4,order:'return',node:null,carry:8,carryType:'wood'});assert.equal(g.walkable(u.x,u.z),false);const x=u.x,z=u.z;g.navBudget=10;g.workerAI(u,.1);assert.ok(Math.hypot(u.x-x,u.z-z)<=u.speed*.12);drive(g,u);assert.equal(u.carry,0);});
test('larger pillage yields are finite transfers from real enemy reserves',()=>{const g=fixture(),b=g.makeBld('warehouse',80,38,1);Object.assign(g.tribe(1),{food:400,wood:200,stone:80});const before=['food','wood','stone'].map(k=>g.tribe(0)[k]+g.tribe(1)[k]);const food=g.tribe(0).food;g.lootBuilding(0,b);assert.equal(g.tribe(0).food-food,140);assert.deepEqual(['food','wood','stone'].map(k=>g.tribe(0)[k]+g.tribe(1)[k]),before);});
test('a local trader negotiates a small surplus without exporting winter necessities',async()=>{const {quoteShipment}=await import('../src/game/barter.ts');const g=fixture();g.state.buildings.push(g.makeBld('townhall',80,38,1));g.vision.fill(1);Object.assign(g.tribe(0),{food:300});Object.assign(g.tribe(1),{food:0,wood:28,hostile:false,tradeCd:0});const q=quoteShipment(g,1,'food','wood',30);assert.ok(q.deal);assert.equal(q.deal.getAmt,4);assert.match(q.reason,/smaller/);g.tribe(1).wood=24;assert.equal(quoteShipment(g,1,'food','wood',30).deal,null);});

test('prosperity milestones keep the evolving settlement playable',()=>{const g=fixture();g.tribe(0).age=5;g.state.raidWave=4;for(let i=0;i<30;i++){const u=g.spawnUnit('worker',15+i,48,0);u.militia=true;}g.checkVictory();assert.equal(g.state.ended,null);});
test('rival growth reserves include children maturing before the next harvest',async()=>{const {growthFoodNeed}=await import('../src/game/pantry.ts');const g=fixture();g.state.units=[];for(let i=0;i<6;i++){const u=g.spawnUnit('worker',0,48,1);u.maturesAt=g.state.time+1;}const maturing=growthFoodNeed(g,1);for(const u of g.state.units)u.maturesAt=g.state.time+360;assert.ok(growthFoodNeed(g,1)<maturing);assert.ok(maturing>200);});

test('severe storms are bounded interruptions, including loaded old storms',()=>{const g=fixture();g.state.weather='storm';g.state.weatherT=290;g.tickWeather(1);assert.ok(g.state.weatherT<=49);g.state.weatherT=0;const random=Math.random;try{Math.random=()=>.44;g.tickWeather(1);}finally{Math.random=random;}if(g.state.weather==='storm')assert.ok(g.state.weatherT<=50);});

test('preservation work proceeds from a reachable warehouse corner',()=>{const g=fixture(),u=g.state.units[0],b=g.makeBld('warehouse',30,38,0);g.state.buildings.push(b);g.tribe(0).food=150;g.tribe(0).wood=40;g.rebuildWalk();Object.assign(u,{x:40,z:50,y:4,order:'gather',node:b,job:'food',gatherT:0});for(let i=0;i<900&&!b.storeCare;i++){g.state.time+=.1;g.navBudget=10;g.workerAI(u,.1);}assert.ok(b.storeCare>0);assert.equal(g.tribe(0).wood,39);});

test('projectile destruction transfers finite loot exactly once',()=>{const g=fixture(),u=g.state.units[0],b=g.makeBld('warehouse',15,38,1);g.state.buildings.push(b);b.hp=.1;g.tribe(1).food=100;const food=g.tribe(0).food;g.fireArrow(u,b);for(let i=0;i<100;i++)g.updateProjectiles(.1);assert.equal(b.hp,0);assert.equal(g.tribe(0).food,food+35);assert.equal(g.tribe(1).food,65);g.lootBuilding(0,b);assert.equal(g.tribe(0).food,food+35);});
