import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/game/sim.ts';import {beginWeaponWork,weaponWorkAI,raidLootAI,combatPractice} from '../src/game/warfare.ts';
import {decodeGame,encodeGame} from '../src/game/persistence.ts';
function fixture(){const g=new Game();g.reset(123456);g.enterIsland();g.world.heights.fill(4);g.state.buildings=[g.makeBld('townhall',0,38,0),g.makeBld('warehouse',80,38,1)];g.state.units=[];const u=g.spawnUnit('worker',0,50,0);g.state.weather='clear';g.state.paused=false;g.clockState=()=>({period:'Afternoon'});g.vision.fill(2);g.rebuildWalk();return {g,u};}
function work(g,u,seconds){for(let i=0;i<seconds*10;i++){g.state.time+=.1;g.navBudget=10;g.workerAI(u,.1);}}
test('stone weapons require actual civilian labor and walking; interrupted progress survives a save',()=>{let {g,u}=fixture();g.tribe(0).wood=50;g.tribe(0).stone=20;const stock=g.tribe(0).spears;assert.equal(beginWeaponWork(g,'spear'),true);assert.equal(g.tribe(0).spears,stock);assert.equal(g.tribe(0).wood,46);work(g,u,12);assert.ok(u.weaponWork.progress>0&&u.weaponWork.progress<24);u.order='move';const progress=u.weaponWork.progress;weaponWorkAI(g,u,30);assert.equal(u.weaponWork.progress,progress);g=decodeGame(encodeGame(g));g.world.heights.fill(4);g.rebuildWalk();g.clockState=()=>({period:'Afternoon'});u=g.state.units.find(u=>u.team===0);u.order='hold';work(g,u,150);assert.equal(g.tribe(0).spears,stock+1);assert.equal(u.weaponWork,undefined);assert.equal(g.popNow(0),1);});
test('bows are available in Stone Age; blades require adopted age and a forge',()=>{const {g}=fixture();assert.equal(beginWeaponWork(g,'bow'),true);assert.equal(beginWeaponWork(g,'blade'),false);g.tribe(0).age=1;g.tribe(0).copper=20;assert.equal(beginWeaponWork(g,'blade'),false);});
test('arming selected adults neither heals nor recruits, and remote/carried supplies cannot be transformed into weapons',()=>{const {g,u}=fixture();const v=g.spawnUnit('worker',12,50,0);u.hp=17;u.selected=true;g.tribe(0).spears=5;assert.equal(g.callToArms(),1);assert.equal(u.hp,17);assert.equal(u.militia,true);assert.equal(v.type,'worker');const gear=g.tribe(0).spears;g.standDown();assert.equal(u.hp,17);assert.equal(g.tribe(0).spears,gear+1);u.carry=8;u.carryType='wood';assert.equal(g.callToArms(),0);u.carry=0;u.x=100;assert.equal(g.callToArms(),0);});
test('pillage conserves enemy stock as ruin cargo, then carried goods, then delivered goods',()=>{const {g,u}=fixture();u.type='spearman';u.militia=true;u.x=80;u.z=41;u.pillage=1;u.order='attackmove';const b=g.state.buildings[1];b.hp=0;g.tribe(1).food=100;const food=g.tribe(0).food;g.lootBuilding(0,b);g.rebuildWalk();assert.equal(g.tribe(0).food,food);assert.equal(g.tribe(1).food,65);assert.equal(b.raidLoot.food,35);assert.equal(raidLootAI(g,u,.1),true);assert.equal(u.carry,12);assert.equal(b.raidLoot.food,23);assert.equal(u.order,'return');assert.equal(g.tribe(0).food,food);work(g,u,90);assert.equal(u.carry,0);assert.equal(g.tribe(0).food,food+12);assert.equal(u.order,'hold');assert.equal(g.tribe(1).food+b.raidLoot.food+g.tribe(0).food,100+food);});
test('raid loot and an armed returning carrier survive save/load',()=>{let {g,u}=fixture();const b=g.state.buildings[1];b.hp=0;g.tribe(1).wood=100;g.tribe(1).food=0;g.lootBuilding(0,b);Object.assign(u,{x:80,z:41,type:'spearman',militia:true,pillage:1,order:'attackmove'});raidLootAI(g,u,.1);g=decodeGame(encodeGame(g));g.world.heights.fill(4);g.rebuildWalk();u=g.state.units.find(u=>u.team===0);assert.ok(u.carry>0);const stock=g.tribe(0).wood;const carried=u.carry;work(g,u,90);assert.equal(g.tribe(0).wood,stock+carried);assert.equal(g.state.buildings[1].lootClaimed,true);});
test('archer destroys a store through the same finite loot and hostility rules as melee',()=>{const {g,u}=fixture();const b=g.state.buildings[1];b.hp=1;g.tribe(1).food=100;const food=g.tribe(0).food;g.fireArrow(u,b);for(let i=0;i<15;i++)g.updateProjectiles(.1);assert.equal(b.hp,0);assert.equal(b.raidLoot.food,35);assert.equal(g.tribe(0).food,food);assert.equal(g.tribe(1).hostile,true);});
test('practice uses a real barracks, improves skill and preserves health/population/equipment',()=>{const {g,u}=fixture();g.tribe(0).age=1;g.tribe(0).food=1000;u.hp=17;u.drill=0;u.order='hold';work(g,u,50);assert.equal(u.drill,0);const b=g.makeBld('barracks',20,38,0);g.state.buildings.push(b);g.rebuildWalk();work(g,u,70);assert.equal(u.combatXP,6);assert.ok(combatPractice(u)>1);assert.equal(u.type,'worker');assert.equal(u.hp,17);assert.equal(g.popNow(0),1);});
test('malformed weapon or loot saves are rejected without touching an active village',()=>{const {g,u}=fixture();u.weaponWork={kind:'spear',progress:100,duration:24,workplace:1};assert.throws(()=>decodeGame(encodeGame(g)));u.weaponWork=undefined;g.state.buildings[1].raidLoot={wood:-1};assert.throws(()=>decodeGame(encodeGame(g)));});
test('raid reaches a discovered enemy, declares hostility only on arrival, destroys and hauls home in the real loop',()=>{const {g,u}=fixture();u.selected=true;g.callToArms();u.dmg=30;const b=g.state.buildings[1];b.hp=60;g.tribe(1).food=100;g.vision.fill(1);const food=g.tribe(0).food;g.issuePillage(b);assert.equal(g.tribe(1).hostile,false);for(let i=0;i<1500;i++){g.state.time+=.1;g.navBudget=10;g.updateVision();if(g.state.walkDirty)g.rebuildWalk();if(!raidLootAI(g,u,.1)){if(u.order==='return')g.workerAI(u,.1);else g.combatAI(u,.1);}g.updateProjectiles(.1);}assert.equal(b.hp,0);assert.equal(g.tribe(1).hostile,true);assert.ok(g.tribe(0).food>food);assert.equal(u.carry,0);assert.equal(u.order,'hold');});

test('friendly and already defeated targets cannot grant free combat practice',()=>{const {g,u}=fixture();const ally=g.spawnUnit('worker',2,50,0);g.dealDamage(u,ally);g.fireArrow(u,ally);assert.equal(u.combatXP,undefined);assert.equal(g.state.projectiles.length,0);ally.team=1;ally.hp=0;g.dealDamage(u,ally);assert.equal(u.combatXP,undefined);});

test('weapon orders reserve the clicked workplace rather than a different nearby hall',()=>{
  const g=new Game();g.reset(123456);g.enterIsland();g.world.heights.fill(4);g.state.weather='clear';g.state.buildings=[];
  const a=g.makeBld('townhall',0,38,0),b=g.makeBld('townhall',45,38,0);g.state.buildings.push(a,b);g.rebuildWalk();
  const u=g.state.units.find(u=>u.team===0&&u.type==='worker');g.state.units=[u];Object.assign(u,{x:10,z:48,y:4,order:'idle',carry:0});
  Object.assign(g.tribe(0),{wood:30,stone:10});assert.equal(g.craftWeapon('spear',b.id),true);assert.equal(u.weaponWork.workplace,b.id);
  const stock=g.tribe(0).wood;assert.equal(g.craftWeapon('spear',999999),false);assert.equal(g.tribe(0).wood,stock);
});
